version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: phpeak-mailhog
      ports:
        - "8025:8025"

    redis:
      image: redis:alpine
      container_name: phpeak-redis

    mysql:
      image: mysql:8.0
      container_name: phpeak-mysql
      working_dir: /phpeak
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=phpeak
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "33066:3306"

    webserver:
      image: nginx:alpine
      container_name: phpeak-webserver
      working_dir: /application
      volumes:
          - ../:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "81:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: phpeak-php-fpm
      working_dir: /application
      volumes:
        - ../:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8/fpm/conf.d/99-overrides.ini

